language: bash
sudo: required

on:
  tags: true

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - echo 'DOCKER_OPTS="--experimental=true"' | sudo tee /etc/default/docker
  - sudo service docker restart

script:
  - sudo make build
  - sudo make test
  - docker save dalee/baseimage:latest | gzip > ${CACHE_BASEIMAGE}
  - docker save dalee/php-5.6:latest | gzip > ${CACHE_PHP56}
  - docker save dalee/nodejs-6:latest | gzip > ${CACHE_NODEJS6}

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then sudo make publish; fi
  - if [ ! -z "$TRAVIS_TAG" ]; then sudo make publish; fi
