language: bash
sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - echo 'DOCKER_OPTS="--experimental=true"' | sudo tee /etc/default/docker
  - sudo service docker restart

jobs:
  include:
    - stage: build
      script: sudo make build
    - stage: test
      script: sudo make test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then sudo make publish; fi
