sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - echo 'DOCKER_OPTS="--experimental=true"' > /etc/default/docker
  - sudo service docker restart

script:
  - docker --version
  - sudo make build
  - sudo make test

after_success:
  - echo "ok"
