FROM debian:12-slim
WORKDIR /app/
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN apt-get -y update && \
    apt-get -y install locales php8.2 \
    php8.2-bcmath \
    php8.2-cli \
    php8.2-common \
    php8.2-curl \
    php8.2-dom \
    php8.2-gd \
    php8.2-intl \
    php8.2-mbstring \
    php8.2-mysql \
    php8.2-pgsql \
    php8.2-soap \
    php8.2-xml \
    php8.2-zip

RUN sed -i 's/^# *\(\(ru_RU\|en_US\).UTF-8\)/\1/' /etc/locale.gen && locale-gen && update-locale

RUN apt-get clean && \
    apt-get autoremove --purge && \
    rm -rf \
    /var/lib/apt/lists/* \
    /usr/share/doc/* \
    /usr/share/man/* \
    /usr/share/info/* \
    /usr/share/lintian/* \
    /usr/share/locale/* \
    /usr/lib/systemd/* \
    /var/log/alternatives.log \
    /var/log/bootstrap.log \
    /var/log/dpkg.log \
    /var/log/apt/* \
    /tmp/*

CMD ["php", "-a"]
