FROM debian:12-slim
WORKDIR /app/
EXPOSE 9000
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN apt-get update -y && apt-get -y install apt-transport-https curl locales unzip git && \
    curl -sSLo /usr/share/keyrings/deb.sury.org-php.gpg https://packages.sury.org/php/apt.gpg && \
    sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ bookworm  main" > /etc/apt/sources.list.d/php.list'

RUN apt-get update -y && apt-get -y install php8.3 \
    php8.3-bcmath \
    php8.3-cli \
    php8.3-common \
    php8.3-curl \
    php8.3-dom \
    php8.3-gd \
    php8.3-intl \
    php8.3-mbstring \
    php8.3-mysql \
    php8.3-pgsql \
    php8.3-soap \
    php8.3-xml \
    php8.3-zip \
    php8.3-redis \
    php8.3-fpm

RUN sed -i 's/^# *\(\(ru_RU\|en_US\).UTF-8\)/\1/' /etc/locale.gen && locale-gen && update-locale
RUN sed -i 's/^listen = .\+/listen = 9000/g' /etc/php/8.3/fpm/pool.d/www.conf

RUN apt-get clean && \
    apt-get autoremove --purge && \
    rm -rf \
    /var/lib/apt/lists/* \
    /usr/share/doc/* \
    /usr/share/man/* \
    /usr/share/info/* \
    /usr/share/lintian/* \
    /usr/share/locale/* \
    /usr/lib/systemd/* \
    /var/log/alternatives.log \
    /var/log/bootstrap.log \
    /var/log/dpkg.log \
    /var/log/apt/* \
    /tmp/*

#CMD ["php-fpm8.3", "-F"]
CMD ["php", "-a"]
