FROM phusion/baseimage:18.04-1.0.0

# Image default properties
ENV DEBIAN_FRONTEND=noninteractive \
    LOCALE=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    COMPOSER_ALLOW_SUPERUSER=1

# Install
RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php && \
    apt-get -qq -y update && \
    apt-get -qq -y \
    install nginx git unzip make \
    php7.3-common \
    php7.3-cli \
    php7.3-fpm \
    php7.3-pgsql \
    php7.3-mysql \
    php7.3-gd \
    php7.3-bz2 \
    php7.3-zip \
    php7.3-json \
    php7.3-xml \
    php7.3-curl \
    php7.3-intl \
    php7.3-mbstring \
    php7.3-bcmath && \
    update-alternatives --set php /usr/bin/php7.3 && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    locale-gen ru_RU.UTF-8 && update-locale

# Cleanup
RUN apt-get -qq clean && \
    apt-get -qq autoremove --purge && \
    rm -rf \
    /etc/php/8.0 \
    /var/lib/apt/lists/* \
    /usr/share/doc/* \
    /usr/share/man/* \
    /usr/share/info/* \
    /usr/share/lintian/* \
    /usr/share/locale/* \
    /usr/lib/systemd/* \
    /usr/lib/valgrind/* \
    /var/log/alternatives.log \
    /var/log/bootstrap.log \
    /var/log/dpkg.log \
    /var/log/apt/* \
    /tmp/*

