FROM debian:trixie-slim
WORKDIR /app/
EXPOSE 9000
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN apt-get update -y && apt-get -y install apt-transport-https curl locales unzip git && \
    curl -sSLo /usr/share/keyrings/deb.sury.org-php.gpg https://packages.sury.org/php/apt.gpg && \
    sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ trixie main" > /etc/apt/sources.list.d/php.list'

RUN apt-get update -y && apt-get -y install php8.4 \
    php8.4-bcmath \
    php8.4-cli \
    php8.4-common \
    php8.4-curl \
    php8.4-dom \
    php8.4-gd \
    php8.4-intl \
    php8.4-mbstring \
    php8.4-mysql \
    php8.4-pgsql \
    php8.4-soap \
    php8.4-xml \
    php8.4-zip \
    php8.4-redis \
    php8.4-fpm

RUN sed -i 's/^# *\(\(ru_RU\|en_US\).UTF-8\)/\1/' /etc/locale.gen && locale-gen && update-locale
RUN sed -i 's/^listen = .\+/listen = 9000/g' /etc/php/8.4/fpm/pool.d/www.conf

RUN apt-get clean && \
    apt-get autoremove --purge && \
    rm -rf \
    /var/lib/apt/lists/* \
    /usr/share/doc/* \
    /usr/share/man/* \
    /usr/share/info/* \
    /usr/share/lintian/* \
    /usr/share/locale/* \
    /usr/lib/systemd/* \
    /var/log/alternatives.log \
    /var/log/bootstrap.log \
    /var/log/dpkg.log \
    /var/log/apt/* \
    /tmp/*

#CMD ["php-fpm8.4", "-F"]
CMD ["php", "-a"]
