FROM dalee/baseimage:latest

ENV DEBIAN_FRONTEND=noninteractive \
    LOCALE=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    COMPOSER_ALLOW_SUPERUSER=1

#
# php: 4F4EA0AAE5267A6C
#
RUN echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" > /etc/apt/sources.list.d/php7.list && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C && \
    apt-get -qq update

# Install
RUN apt-get -qq install -y \
    php7.2-common \
    php7.2-cli \
    php7.2-fpm \
    php7.2-pgsql \
    php7.2-mysql \
    php7.2-gd \
    php7.2-bz2 \
    php7.2-zip \
    php7.2-json \
    php7.2-xml \
    php7.2-curl \
    php7.2-intl \
    php7.2-mbstring \
    php7.2-bcmath \
    php7.2-soap \
    php7.2-memcached \
    php-redis \
    php7.2-xdebug

# Install composer
RUN curl "https://getcomposer.org/installer" -o /tmp/composer-installer.php && \
    chmod 755 /tmp/composer-installer.php && \
    php /tmp/composer-installer.php --install-dir=/tmp && \
    mv /tmp/composer.phar /usr/local/bin/composer && \
    chmod 755 /usr/local/bin/composer && \
    rm /tmp/composer-installer.php

# Disable composer warning and xdebug extension
RUN echo "\nexport COMPOSER_ALLOW_SUPERUSER=1\n" >> /root/.bashrc && \
    echo ";zend_extension=xdebug.so\n" > /etc/php/7.2/cli/conf.d/20-xdebug.ini && \
    echo ";zend_extension=xdebug.so\n" > /etc/php/7.2/fpm/conf.d/20-xdebug.ini

# Cleanup
RUN apt-get -qq clean && \
    apt-get -qq autoremove --purge && \
    rm -rf \
    /etc/php/5.6 \
    /etc/php/7.0 \
    /etc/php/7.1 \
    /var/lib/apt/lists/* \
    /usr/share/doc/* \
    /usr/share/man/* \
    /usr/share/info/* \
    /usr/share/lintian/* \
    /usr/share/locale/* \
    /usr/lib/systemd/* \
    /usr/lib/valgrind/* \
    /var/log/alternatives.log \
    /var/log/bootstrap.log \
    /var/log/dpkg.log \
    /var/log/apt/* \
    /tmp/*
