#!/usr/bin/env bash
set -eo pipefail

#
# fetching current options
#
RELAY=""
HOST="docker"
if [ ! -z "${NULLMAILER_REMOTES}" ]; then RELAY="${NULLMAILER_REMOTES}"; fi
if [ ! -z "${NULLMAILER_HOSTNAME}" ]; then HOST="${NULLMAILER_HOSTNAME}"; fi

mkdir -p /etc/nullmailer
echo "${RELAY}" > "/etc/nullmailer/remotes"
echo "${HOST}" > "/etc/nullmailer/me"
chmod 0600 /etc/nullmailer/remotes /etc/nullmailer/me
chown mail:root /etc/nullmailer/remotes /etc/nullmailer/me

mkdir -p /var/spool/nullmailer/queue /var/spool/nullmailer/tmp
mkfifo /var/spool/nullmailer/trigger
chown mail:root -R /var/spool/nullmailer
