#!/usr/bin/env bash
set -eo pipefail

#
# if SENDMAIL_HOST is set, forward mail to that host.
# if SENDMAIL_PORT is set, use port from environment.
#
if [ -z "${SENDMAIL_HOST}" ]; then
    echo "==> Environment variable SENDMAIL_HOST is not set, skipping configuration..."
    exit 0
fi
if [ -z "${SENDMAIL_PORT}" ]; then
    SENDMAIL_PORT="25"
fi

SENDMAIL_FROM=""
if [ ! -z "${SENDMAIL_DOMAIN}" ]; then
    SENDMAIL_FROM="from nobody@${SENDMAIL_DOMAIN}"
fi

#
# create system-wide configuration file.
#
SENDMAIL_HOST=${SENDMAIL_HOST} \
SENDMAIL_PORT=${SENDMAIL_PORT} \
SENDMAIL_FROM=${SENDMAIL_FROM} \
envsubst <<"EOF" > /etc/msmtprc
defaults
account default
host $SENDMAIL_HOST
port $SENDMAIL_PORT

$SENDMAIL_FROM
EOF

#
# symlink /usr/sbin/sendmail => /usr/bin/msmtp
#
ln -s /usr/bin/msmtp /usr/sbin/sendmail
